SELECT 
    d.AIRCRAFT_MODEL,
    d.AIRCRAFT_MANUFACTURER,
    d.SEAT_CAPACITY,
    AVG(f.AVERAGE_RATING) AS avg_rating,
    COUNT(*) AS review_count
FROM SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED f
JOIN SKYTRAX_REVIEWS_DB.MARTS.DIM_AIRCRAFT d
    ON f.AIRCRAFT_ID = d.AIRCRAFT_ID
WHERE f.AIRLINE = 'Spirit Airlines'
GROUP BY d.AIRCRAFT_MODEL, d.AIRCRAFT_MANUFACTURER, d.SEAT_CAPACITY
ORDER BY review_count DESC;
