SELECT 
    'Origin' AS location_type,
    d.AIRPORT AS airport,
    AVG(f.AVERAGE_RATING) AS avg_rating,
    COUNT(*) AS review_count
FROM SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED f
JOIN SKYTRAX_REVIEWS_DB.MARTS.DIM_LOCATION d
    ON f.ORIGIN_LOCATION_ID = d.LOCATION_ID
WHERE f.AIRLINE = 'Spirit Airlines'
  AND f.ORIGIN_LOCATION_ID IS NOT NULL
  AND d.AIRPORT != 'Unknown'
GROUP BY d.AIRPORT

UNION ALL

SELECT 
    'Destination' AS location_type,
    d.AIRPORT AS airport,
    AVG(f.AVERAGE_RATING) AS avg_rating,
    COUNT(*) AS review_count
FROM SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED f
JOIN SKYTRAX_REVIEWS_DB.MARTS.DIM_LOCATION d
    ON f.DESTINATION_LOCATION_ID = d.LOCATION_ID
WHERE f.AIRLINE = 'Spirit Airlines'
  AND f.DESTINATION_LOCATION_ID IS NOT NULL
  AND d.AIRPORT != 'Unknown'
GROUP BY d.AIRPORT;
