SELECT 
  DATE_TRUNC('year', DATE_SUBMITTED_ID) AS review_year, 
  AVG(AVERAGE_RATING) AS avg_rating, 
  COUNT(*) AS review_count 
FROM SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED 
WHERE AIRLINE = 'Spirit Airlines' GROUP BY 1 ORDER BY 1;